DATALOADER:
  TRAIN_X:
    SAMPLER: "SeqDomainSampler"
    BATCH_SIZE: 48 # 16 images per domain
  TRAIN_U:
    SAME_AS_X: True
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 4
  RETURN_IMG0: True

OPTIM:
  NAME: "sgd"
  LR: 0.003
  MAX_EPOCH: 20
  LR_SCHEDULER: "cosine"

TRAIN:
  COUNT_ITER: "train_u"
  PRINT_FREQ: 10

##########
# FixMatch
##########
TRAINER:
  STYLEMATCH:
    STRONG_TRANSFORMS: ["random_flip", "randaugment_fixmatch", "normalize", "cutout"]
    C_OPTIM:
      NAME: "sgd"
      LR: 0.01
      MAX_EPOCH: 20
      LR_SCHEDULER: "cosine"
    INFERENCE_MODE: "deterministic"
    ADAIN_DECODER: "weights/decoder.pth"
    ADAIN_VGG: "weights/vgg_normalised.pth"
    APPLY_AUG: True
    APPLY_STY: False
    CLASSIFIER: "normal"
